const data = [
    {
        header: "Sr. Dev @ UBC BizTech, building features that empower attendees",
        href: "biztech",
        src: "/grid/biztech.webm",
        subheader: "Web app and dev features",
        tech_stack: "AWS (DynamoDB, S3, Lambda), Serverless",
    },
    {
        header: "ChalkMD, an open-sourced Obsidian port written in Go",
        href: "chalkmd",
        src: "/grid/chalkmd.gif",
        subheader: "An open-sourced Obsidian port in Go",
        tech_stack: "Go, Wails, Vite, Tiptap, Markdown",
    },
    {
        header: "Dev @ Mecha Mayhem, Canada's largest robotics competition",
        href: "mecha-mayhem",
        src: "/grid/laptop.mp4",
        subheader: "Canada's largest robotics competition",
        tech_stack: "AWS, Firebase, Computer Vision",
    },
    {
        header: "Event Control, network failure tolerant tournament managers",
        href: "event-control",
        src: "/grid/ec.png",
        subheader: "VRC5 Event Control and Orchestration",
        tech_stack: "Go, SQLite, Mochi MQTT",
    },
    {
        header: "ChooChoo, distributed KV store packaged in a single .exe file",
        href: "choochoo",
        src: "/grid/choochoo.png",
        subheader: "A pocket-sized distributed key-value store in Go",
        tech_stack: "Go, BoltDB, Hashicorp Raft",
    },
    {
        header: "npm-blast-radius, large-scale npm dependency graph pipelines",
        href: "event-control",
        src: "/grid/ec.png",
        subheader: "VRC5 Event Control and Orchestration",
        tech_stack: "Python, Apache Spark",
    },
    {
        header: "Polaris, event navigation and mapping that doesnt suck",
        href: "polaris",
        src: "/grid/polaris.png",
        subheader: "Hack the North 2024",
        tech_stack: "React, Node.js, Firebase, TailwindCSS",
    },
    {
        header: "Oniva, hiking trails personalized to your mood",
        href: "oniva",
        src: "/grid/oniva.png",
        subheader: "Cloud Vision-based Activity Planning",
        tech_stack: "React, Node.js, Firebase, MongoDB",
    },
    {
        header: "MPGA-Photoeditor, an image editor with granular control",
        href: "mpga",
        src: "/grid/mpga.png",
        subheader: "Customized Image Editor",
        tech_stack: "Java, Java Swing",
    },
    {
        header: "CacheYouLater, mobile virtual geocaching with friends",
        href: "cyl",
        src: "/grid/cyl.png",
        subheader: "Virtual Gamified Geocaching",
        tech_stack: "Next, Node.js, Pocketbase, TailwindCSS",
    },
    {
        header: "Examif.AI, LLM-powered exam material generation",
        href: "examifai",
        src: "/grid/examifai.png",
        subheader: "LLM-powered exam material generation",
        tech_stack: "React, Node.js, MongoDB, Gumloop",
    },
    {
        header: "SWC-DB, a backend to replace outdated paper sign-outs",
        href: "swcdb",
        src: "/grid/swc.png",
        subheader: "Semantic search-enabled inventory tracker",
        tech_stack: "Python, Flask, Discord.py",
    },
    {
        header: "Team 210X, provincials-winning autonomous routines",
        href: "vex",
        src: "/grid/vex-robotics.png",
        subheader: "2022 VEX Robotics Provincial Champions",
        tech_stack: "C++, PROS, LVGL, OkapiLib",
    },

    {
        header: "Bomb Party Bot, OCR-powered bot for cheating in Bomb Party",
        href: "bomb-party",
        src: "/grid/bomb-party.png",
        subheader: "OCR-based bot for Bomb Party",
        tech_stack: "Python, OpenCV, TesseractOCR",
    },
];

export default data;
