

import { Inconsolata, Poppins } from "next/font/google";
import Simulation from "@/components/ui/three-components/Simulation";
import "./globals.css";

const inconsolata = Inconsolata({
    display: "swap",
    subsets: ["latin"],
    variable: "--font-inconsolata",
    weight: ["200", "400", "700"], // Choose the weights you need
});

const poppins = Poppins({
    display: "swap",
    subsets: ["latin"],
    variable: "--font-poppins",
    weight: ["300", "400", "600", "700"], // Choose the weights you need
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${inconsolata.variable} ${poppins.variable} antialiased text-white font-mono`}
            >
                <Simulation>{children}</Simulation>
            </body>
        </html>
    );
}
