import { Inconsolata, Poppins } from "next/font/google";
import "./globals.css";
import ClientSimulation from "@/components/ClientSimulation";

const inconsolata = Inconsolata({
    display: "swap",
    subsets: ["latin"],
    variable: "--font-inconsolata",
    weight: ["200", "400", "700"], // Choose the weights you need
});

const poppins = Poppins({
    display: "swap",
    subsets: ["latin"],
    variable: "--font-poppins",
    weight: ["300", "400", "600", "700"], // Choose the weights you need
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${inconsolata.variable} ${poppins.variable} antialiased text-white font-mono`}
            >
                <ClientSimulation />
                <div className="relative z-20 pointer-events-auto min-h-screen">
                    {children}
                </div>
            </body>
        </html>
    );
}
